stages:
  preprocessing_flats:
    cmd: python -m src.data.preprocessing_flats
    deps:
    - src/data/preprocessing_flats.py
    - data/raw/flats.csv
    outs:
    - data/interim/flats.csv
  preprocessing_houses:
    cmd: python -m src.data.preprocessing_houses
    deps:
    - src/data/preprocessing_houses.py
    - data/raw/houses.csv
    outs:
    - data/interim/houses.csv
  merge_flats_and_houses:
    cmd: python -m src.data.merge_flats_and_houses
    deps:
    - src/data/merge_flats_and_houses.py
    - data/raw/flats.csv
    - data/raw/houses.csv
    outs:
    - data/interim/gurgaon_properties.csv
  preprocessing_level_2:
    cmd: python -m src.data.preprocessing_level_2
    deps:
    - src/data/preprocessing_level_2.py
    - data/interim/gurgaon_properties.csv
    outs:
    - data/interim/gurgaon_properties_cleaned_v1.csv
  feature_engineering:
    cmd: python -m src.features.feature_engineering
    deps:
    - src/features/feature_engineering.py
    - data/interim/gurgaon_properties_cleaned_v1.csv
    - data/raw/appartments.csv
    outs:
    - data/interim/gurgaon_properties_cleaned_v2.csv
  outlier_treatment:
    cmd: python -m src.features.outlier_treatment
    deps:
    - src/features/outlier_treatment.py
    - data/interim/gurgaon_properties_cleaned_v2.csv
    outs:
    - data/interim/gurgaon_properties_outlier_treated.csv
  missing_value_imputation:
    cmd: python -m src.features.missing_value_imputation
    deps:
    - src/features/missing_value_imputation.py
    - data/interim/gurgaon_properties_outlier_treated.csv
    outs:
    - data/interim/gurgaon_properties_missing_value_imputation.csv
  feature_selection:
    cmd: python -m src.features.feature_selection
    deps:
    - src/features/feature_selection.py
    - data/interim/gurgaon_properties_missing_value_imputation.csv
    outs:
    - data/processed/gurgaon_properties_post_feature_selection.csv
  split_data:
    cmd: python -m src.features.split_data
    deps:
    - src/features/split_data.py
    - data/processed/gurgaon_properties_post_feature_selection.csv
    params:
    - split_data.test_size
    - split_data.random_state
    outs:
    - data/processed/train.csv
    - data/processed/test.csv
  model_building:
    cmd: python -m src.models.model_building
    deps:
    - src/models/model_building.py
    - data/processed/train.csv
    params:
    - model_building.n_estimators
    - model_building.max_depth
    - model_building.max_samples
    - model_building.max_features
    outs:
    - models/real_estate_predictor.pkl
  model_evaluation:
    cmd: python -m src.models.model_evaluation
    deps:
    - src/models/model_evaluation.py
    - data/processed/test.csv
    - models/real_estate_predictor.pkl
  data_visualization:
    cmd: python -m src.visualization.data_viz
    deps:
    - src/visualization/data_viz.py
    - data/raw/latlong.csv
    - data/interim/gurgaon_properties_missing_value_imputation.csv
    - data/interim/gurgaon_properties.csv
    outs:
    - models/data_viz1.csv
    - models/wordcloud_df.pkl
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
