stages:
  preprocessing_flats:
    cmd: python -m src.data.preprocessing_flats
    deps:
    - src/data/preprocessing_flats.py
    - data/raw/flats.csv
    outs:
    - data/interim/flats.csv
  preprocessing_houses:
    cmd: python -m src.data.preprocessing_houses
    deps:
    - src/data/preprocessing_houses.py
    - data/raw/houses.csv
    outs:
    - data/interim/houses.csv
  merge_flats_and_houses:
    cmd: python -m src.data.merge_flats_and_houses
    deps:
    - src/data/merge_flats_and_houses.py
    - data/raw/flats.csv
    - data/raw/houses.csv
    outs:
    - data/interim/gurgaon_properties.csv
  preprocessing_level_2:
    cmd: python -m src.data.preprocessing_level_2
    deps:
    - src/data/preprocessing_level_2.py
    - data/interim/gurgaon_properties.csv
    outs:
    - data/interim/gurgaon_properties_cleaned_v1.csv
  feature_engineering:
    cmd: python -m src.features.feature_engineering
    deps:
    - src/features/feature_engineering.py
    - data/interim/gurgaon_properties_cleaned_v1.csv
    - data/raw/appartments.csv
    outs:
    - data/interim/gurgaon_properties_cleaned_v2.csv
  outlier_treatment:
    cmd: python -m src.features.outlier_treatment
    deps:
    - src/features/outlier_treatment.py
    - data/interim/gurgaon_properties_cleaned_v2.csv
    outs:
    - data/interim/gurgaon_properties_outlier_treated.csv
